version: '2'

networks:
  jenkins-network:
    driver: bridge

services:
  jenkins:
    container_name: jenkins
    build: "jenkins/"
    stdin_open: true
    tty: true
    depends_on:
      - sonarqube
    links:
      - sonarqube
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    networks:
      - jenkins-network
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ~/.m2:/var/jenkins_home/.m2
  
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
     - "9000:9000"
    links:
     - db
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    networks:
      - jenkins-network
    volumes_from:
     - plugins
  
  db:
    image: postgres
    container_name: postgres
    volumes_from:
      - datadb
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
    networks:
      - jenkins-network
    ports:
     - "5432:5432"
  
  datadb:
    image: postgres
    container_name: plugins_postgres
    networks:
      - jenkins-network
    volumes:
      - /var/lib/postgresql
    command: /bin/true
  
  plugins:
    image: sonarqube
    container_name: plugins_sonarqube
    networks:
      - jenkins-network
    volumes:
     - /opt/sonarqube/extensions
     - /opt/sonarqube/lib/bundled-plugins
    command: /bin/true
